### ISSUE TITLE
Questions about simulation

### ISSUE THREAD

**Issue by wgb-256** [yuyichao/digitaljs_code#1]
Hi,
I appreciate for your great work.
I could use your extension on VSCode basically but I'd like to ask a few questions for more understanding.

- Is there specific unit of time on the simulation?
- Are there any ways to change time range to display waveform? (It's prohibited by default)
- Do you have some documents of the detail of SYNTHESIS view that has "Optimize in Yosys", "Simplify diagram" and so on?
- Are there any commands to search `wire` or `reg` in the diagram?  
Or are there any ways to add them to waveform view exept for clicking blue button on the diagram?

Let me know when you need more info.
Thank you!

**Comment by yuyichao** [comment]
Note that basically all of these should go to https://github.com/tilk/digitaljs since it's not specific to the vscode integration.

> Is there specific unit of time on the simulation?

No, but I believe the gate delay of each component is assumed to be one tick.

> Are there any ways to change time range to display waveform? (It's prohibited by default)

IIRC the numbers are just for display but you you should be able to zoom in and out.

> Do you have some documents of the detail of SYNTHESIS view that has "Optimize in Yosys", "Simplify diagram" and so on?

No, this is a question for digitaljs

> Are there any commands to search wire or reg in the diagram?
> Or are there any ways to add them to waveform view exept for clicking blue button on the diagram?

I don't believe so.

**Comment by wgb-256** [comment]
Thanks for replying to my all questions.
I'm going to look up the project you mentioned as well.
